### PR TITLE
Bump dependencies to k8s 1.11

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
Adding wip as I'm looking at updating `docker/cli` too (and probably before this one to not do a double bump)

**Comment by shin-** [comment]
Is there a risk that this could cause issues with the version(s) vendored in UCP?

**Comment by chris-crone** [comment]
@shin- We're moving to bring ourselves inline with UCP and @vdemeester has made sure that it doesn't break backwards compatibility.

**Comment by silvin-lubecki** [comment]
Please rebase 🐯

**Comment by vdemeester** [comment]
@silvin-lubecki updated to 1.11.1 :wind_chime:

**Pull request merged**
