### PR TITLE
Bump cnab-to-oci and containerd

### PR DESCRIPTION
**Pull request by simonferquel**
**- What I did**

Bumped cnab-to-oci and containerd for better Push support

### CODE REVIEW

**Comment by chris-crone** [comment]
Looks like linting is failing on vendored code:
```console
Linting...
vendor/github.com/containerd/containerd/signals_unix.go:42:17:warning: SignalNum not declared by package unix (gosimple)
vendor/github.com/containerd/containerd/signals_unix.go:42:17:warning: SignalNum not declared by package unix (interfacer)
vendor/github.com/containerd/containerd/signals_unix.go:42:17:warning: SignalNum not declared by package unix (unconvert)
vendor/github.com/containerd/containerd/signals_unix.go:42:17:warning: parameter SignalNum not declared by package unix (unparam)
vendor/github.com/containerd/containerd/signals_unix.go:42:17:warning: SignalNum not declared by package unix (unused)
vendor/github.com/containerd/containerd/signals_unix.go:42:12:error: undefined: unix.SignalNum (vet)
make: *** [Makefile:74: lint] Error 1
docker.Makefile:107: recipe for target 'lint' failed
make: *** [lint] Error 2
script returned exit code 2
```

**Comment by ijc** [comment]
We should stop linting vendored code...

**Comment by silvin-lubecki** [comment]
That's weird, I really thought we already did...

**Comment by ijc** [comment]
We just do `gometalinter --config=gometalinter.json ./...`, TBH I thought that excluded `vendor/` by itself, but I'm never 100% sure which tools do or don't.

**Comment by ijc** [comment]
The current failure though was the network race/flake. I hit redo...

**Comment by simonferquel** [comment]
The problem was that it actually wont build because bumping containerd required us to bump golang/x/sys (added that and amended the original commit)

**Comment by simonferquel** [comment]
@chris-crone @ijc PTAL (CI is green)

**Pull request merged**
