### PR TITLE
Add a seed for better randomness

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

Added a call to `rand.Seed`

Without the seed the rand.Intn will always start from the same place and
return the same application name

**- How to verify it**

Without this change run:
```
$ docker app run APP1
$ docker app run APP2
```
The second one would fail with a message: `Installation "gallant_poitras" already exists, use 'docker app update' instead`

**- A picture of a cute animal (not mandatory)**
image

### CODE REVIEW

**Comment by justincormack** [comment]
Please do not use `math/rand` in any code, just use `crypto/rand`

**Comment by rumpl** [comment]
> Please do not use `math/rand` in any code, just use `crypto/rand`

The call to `rand.Intn` is in [moby](https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go#L5)

**Comment by rumpl** [comment]
This is for random name generation

**Comment by justincormack** [comment]
Hmm, I thought I had fixed that one too, ok will change it there.

**Comment by justincormack** [comment]
Its ok to merge this though, before I change the implementation.

**Pull request merged**
