### PR TITLE
[WIP] Move docker/cli vendoring back to 19.03 branch

### PR DESCRIPTION
**Pull request by chris-crone**
Signed-off-by: Christopher Crone <christopher.crone@docker.com>

**- What I did**
As the [YAML library bump is now in the 19.03 branch](https://github.com/docker/cli/commit/2355349d8b99ea2c15bbdd7f1f203fa078e9bb4e) for the CLI, I've moved our vendoring back to use that.

**- How I did it**
* Update `Gopkg.toml`
* Run `make vendor`

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ndeloof** [comment]
undefined: loader.WithDiscardEnvFiles
https://github.com/docker/cli/commit/821f5ecf53c87a1f391d97c358f08c8d344cda8c
not yet in 19.03

**Comment by chris-crone** [comment]
> undefined: loader.WithDiscardEnvFiles
> docker/cli@821f5ec
> not yet in 19.03

@thaJeztah are there plans to add that to 19.03?

**Comment by thaJeztah** [comment]
> @thaJeztah are there plans to add that to 19.03?

Oh, good one; looks harmless to cherry-pick if, so if you or @ulyssessouza could open a cherry-pick into the 19.03 branch, then _perhaps_ it could still make it

**Comment by chris-crone** [comment]
We can bump this later

**Pull request closed without merging**
