### PR TITLE
Jenkinsfile: use --password-stdin

### PR DESCRIPTION
**Pull request by thaJeztah**
before:

    docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    WARNING! Using --password via the CLI is insecure. Use --password-stdin.
    Login Succeeded

with this PR:

    echo $REGISTRY_PASSWORD | docker login -u "$REGISTRY_USERNAME" --password-stdin
    Login Succeeded

**- How to verify it**

Ehm, don't know; I don't think the Jenkinsfile change will run on this PR (because I'm not an owner in this repo)

**- A picture of a cute animal (not mandatory but encouraged)**

monkey_phone

### CODE REVIEW

**Comment by thaJeztah** [comment]
@ndeloof 🤗

**Comment by thaJeztah** [comment]
Hm... interesting; https://ci.docker.com/teams-dsg/blue/rest/organizations/jenkins/pipelines/dsg/pipelines/app/branches/PR-624/runs/1/nodes/14/log/?start=0

```

+ FOSSA_API_KEY=**** BRANCH_NAME=PR-624 make fossa-analyze
docker run -i --rm -e FOSSA_API_KEY \
	-e GO111MODULE=on \
	-v /home/ubuntu/workspace/dsg_app_PR-624/src/github.com/docker/app/:/go/src/github.com/docker/app \
	-w /go/src/github.com/docker/app \
	dockereng/fossa-analyzer analyze --option all-tags:true --option allow-unresolved:true --branch PR-624
WARNING Could not determine whether module is built: could not run go list:  (exit status 1)
WARNING Module does not appear to be built
FATAL Could not analyze: could not run go list:  (exit status 1)
Makefile:115: recipe for target 'fossa-analyze' failed
make: *** [fossa-analyze] Error 1
script returned exit code 2
```

**Comment by thaJeztah** [comment]
all green now

**Comment by zelahi** [comment]
Yup, I re-triggered it.  Tho I didn't do anything on the fossa side so I'm curious how it happened

**Comment by silvin-lubecki** [comment]
Thank you @thaJeztah ❤️

**Pull request merged**
