### PR TITLE
 render: err out if any setting value is nil after merge.

### PR DESCRIPTION
**Pull request by mnottale**
This allows the application maintainer to define mandatory settings, by giving them the `null` value.

**- What I did**

Err out if any nil value is detected in settings after merge.

**- How to verify it**

e2e test was added

**- Description for the changelog**
- application rendering will now fail if any setting has the nil value. This allows maintainers to define mandatory settings that must be overridden.

### CODE REVIEW

**Comment by ijc** [comment]
> There seem to be an unrelated commit in this PR (renderning of attachments).

I think/assumed this was the contents of #407 upon which this is based and will disappear once that is merged.

**Comment by mnottale** [comment]
Unit test added.

**Comment by vdemeester** [comment]
@chris-crone @garethr what is the status of this PR ?

**Comment by vdemeester** [comment]
Closing as it is stale :sweat_smile:

**Pull request closed without merging**
