### PR TITLE
Create generic reusable tar handling functions

### PR DESCRIPTION
**Pull request by shin-**
Depends on #292 (spurred by https://github.com/docker/app/pull/292#discussion_r205094387)

**- What I did**

Create 2 generic reusable tar handling functions in internal/packager and updated code to use them where applicable

**- How I did it**

```golang
type tarOperation func(*tar.Reader, *tar.Header) error
type tarStatusOperation func(*tar.Reader, *tar.Header) (bool, error)

func handleTar(file io.Reader, handler tarOperation) error {
  // ...
}

func handleTarWithStatus(file io.Reader, handler tarStatusOperation) (bool, error) {
  // ...
}
```

**- How to verify it**

e2e tests should validate that the dependent functions' behavior is unchanged.

**- Description for the changelog**

Improved tar handling code reuse

**- A picture of a cute animal (not mandatory but encouraged)**

```
|￣￣￣￣￣￣￣￣|
|  IS THIS    | 
|   CUTE      | 
|  ENOUGH?    | 
| ＿＿＿＿＿＿__| 
(\__/) || 
(•ㅅ•) || 
/ 　 づ
```

### CODE REVIEW

**Comment by silvin-lubecki** [comment]
Please rebase 🐱

**Comment by silvin-lubecki** [comment]
It seems #329 tries to do the same thing.

**Comment by shin-** [comment]
I'm fine with it if we decide #329 better addresses our needs. This PR lets us do things like only extracting a subset of files and other conditional processing. #329 reuses existing code and will be easier to maintain.

**Comment by silvin-lubecki** [comment]
ping @shin- , is this PR up-to-date?

**Comment by shin-** [comment]
@silvin-lubecki It was competing with #325 which got closed without comment, so I don't know if any  discussion happened and what the outcome was. I'm happy to update this for the new codebase if we decide it's the right direction.

**Pull request closed without merging**
